"""
Overall risk scoring.

This produces an "AI-assisted risk prioritization" score, explicitly NOT a
validated clinical probability (spec section 3). It is a weighted,
fully-auditable combination of the outputs already produced by the organ
priority, interaction, red-flag, and patient-risk engines — nothing here
is generated by a language model.
"""
from __future__ import annotations

INTERACTION_SEVERITY_POINTS = {"Contraindicated": 100, "Major": 75, "Moderate": 45, "Minor": 20, "Unknown": 10}

WEIGHTS = {"organ": 0.40, "interaction": 0.30, "red_flag": 0.20, "patient": 0.10}


def _category(score: int) -> str:
    if score >= 85:
        return "Critical"
    if score >= 65:
        return "High"
    if score >= 40:
        return "Moderate"
    return "Low"


def compute_overall_risk(priority_organs: list[dict], interactions: list[dict],
                          red_flags: list[dict], patient_risk_factors: list[dict]) -> dict:
    organ_component = max((o["relative_priority_percent"] for o in priority_organs), default=0)
    interaction_component = max(
        (INTERACTION_SEVERITY_POINTS.get(i["severity"], 0) for i in interactions), default=0
    )
    red_flag_component = min(100, len(red_flags) * 25)
    patient_component = min(100, len(patient_risk_factors) * 15)

    weighted = (
        organ_component * WEIGHTS["organ"]
        + interaction_component * WEIGHTS["interaction"]
        + red_flag_component * WEIGHTS["red_flag"]
        + patient_component * WEIGHTS["patient"]
    )
    score = round(min(100, weighted))
    category = _category(score)

    drivers = []
    if organ_component:
        top_organ = max(priority_organs, key=lambda o: o["relative_priority_percent"])
        drivers.append(f"highest-priority organ system is {top_organ['organ']} ({top_organ['priority']})")
    if interaction_component:
        top_interaction = max(interactions, key=lambda i: INTERACTION_SEVERITY_POINTS.get(i["severity"], 0))
        drivers.append(f"a {top_interaction['severity'].lower()} drug interaction ({top_interaction['drug_a']} + {top_interaction['drug_b']})")
    if red_flags:
        drivers.append(f"{len(red_flags)} red flag(s) identified")
    if patient_risk_factors:
        drivers.append(f"{len(patient_risk_factors)} patient-specific risk factor(s)")

    explanation = (
        "Score reflects: " + "; ".join(drivers) + "." if drivers
        else "No significant organ toxicity, interaction, red-flag, or patient-specific risk factors were identified for the selected medication(s)."
    )

    return {
        "category": category,
        "priority_score": score,
        "is_validated_score": False,
        "score_label": "AI-assisted risk prioritization — not a validated clinical score",
        "explanation": explanation,
    }
